// swift-tools-version:5.9
// Generated by packages/skia/scripts/build-spm-binaries.ts. Do not edit.
//
// Prebuilt Skia binaries for Apple platforms, 150.0.0.
import PackageDescription

let package = Package(
    name: "react-native-skia-binaries",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(
            name: "SkiaBinaries",
            targets: [
                "libskia",
                "libskottie",
                "libskparagraph",
                "libsksg",
                "libskshaper",
                "libskunicode_core",
                "libskunicode_libgrapheme",
                "libsvg",
            ]
        )
    ],
    targets: [
        .binaryTarget(
            name: "libskia",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libskia.xcframework.zip",
            checksum: "00cea2d8b2f520a220844c9edc43dd1de42aa3280fafcaa13d5db35d8f1c2315"
        ),
        .binaryTarget(
            name: "libskottie",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libskottie.xcframework.zip",
            checksum: "162f0aa0f7286b9a75104809dfab32aeea9f86aab45c529974fe37a761ca071d"
        ),
        .binaryTarget(
            name: "libskparagraph",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libskparagraph.xcframework.zip",
            checksum: "0f2cf51c1ccdb18d8a6e89bf0582c2cd6056777fded3d3a0228240bf1d82c4d2"
        ),
        .binaryTarget(
            name: "libsksg",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libsksg.xcframework.zip",
            checksum: "7a4b6ab1206c2d7bc5e790d43e9efd486a96f3772ec36bc7d2623fbd61937d96"
        ),
        .binaryTarget(
            name: "libskshaper",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libskshaper.xcframework.zip",
            checksum: "146867380205161424a92512e0b93195303b53a9cba70ac78645767fbdaed7ae"
        ),
        .binaryTarget(
            name: "libskunicode_core",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libskunicode_core.xcframework.zip",
            checksum: "deca51d0e0349ee88686268184792dc7b160bdc3a954ff616e0d30aabd36f4f9"
        ),
        .binaryTarget(
            name: "libskunicode_libgrapheme",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libskunicode_libgrapheme.xcframework.zip",
            checksum: "07c403cc52dfd202f2238e34a25e230919b13cea3865aea86315fdec85e37848"
        ),
        .binaryTarget(
            name: "libsvg",
            url: "https://github.com/chrfalch/react-native-skia-binaries/releases/download/150.0.0/libsvg.xcframework.zip",
            checksum: "a67bc3d7413e5537f8477124211a9758c555f6877b3c242ab2867a0f9c5b4272"
        ),
    ]
)
